spring:
  application.name: tax
  datasource:
    url: jdbc:h2:mem:my-tax
    driver-class-name: org.h2.Driver
    username: sa
    password: zxcvzxcv
  jpa:
    hibernate:
      ddl-auto: update
    datasource-platform: org.hibernate.dialect.H2Dialect
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true

server.servlet.encoding:
  charset: UTF-8
  enabled: true
  force: true

# JSON WebToken 설정
jwt:
  header: Authorization
  secret: QGHd2NpKOzvTMjxDHeF5YnmtBDcku9IEb1JGQGNvfJUgnpwZ4pDVynbe31TNZQwd5VWaQGiin4JsFv7e7+pz/w==
  expiration: 3600

springdoc:
  swagger-ui:
    path: /3o3/swagger.html

feign.client.config.default:
  connectionTimeout: 5000
  readTimeout: 5000
  connection-pool: 10



external:
  tax:
    host: https://codetest-v4.3o3.co.kr
    x-api-key: fQL4PtoGRRgj6Q1OZG1WpQ==

